version: '3.0'

expectations:
  population_size: 100000

actions:
  #Study definition 
  generate_study_population_prevalent_2018:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_prevalent_2018
    outputs:
      highly_sensitive:
        cohort: output/input_prevalent_2018.csv

  generate_study_population_prevalent_2019:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_prevalent_2019
    outputs:
      highly_sensitive:
        cohort: output/input_prevalent_2019.csv

  generate_study_population_prevalent_2020:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_prevalent_2020
    outputs:
      highly_sensitive:
        cohort: output/input_prevalent_2020.csv

  generate_study_population_prevalent_2021:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_prevalent_2021
    outputs:
      highly_sensitive:
        cohort: output/input_prevalent_2021.csv

  generate_study_population_prevalent_2022:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_prevalent_2022
    outputs:
      highly_sensitive:
        cohort: output/input_prevalent_2022.csv

  generate_study_population_prevalent_2023:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_prevalent_2023
    outputs:
      highly_sensitive:
        cohort: output/input_prevalent_2023.csv

  generate_study_population_incident:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_incident
    outputs:
      highly_sensitive:
        cohort: output/input_incident.csv      

# Generate datasets for analysis   000 and 001  
  generate_analysis_dataset_prevalent:
    run: stata-mp:latest analysis/000_cr_define_covariates_prevalent.do
    needs: [generate_study_population_prevalent_2018, generate_study_population_prevalent_2019, generate_study_population_prevalent_2020, generate_study_population_prevalent_2021, generate_study_population_prevalent_2022, generate_study_population_prevalent_2023]
    outputs:
      highly_sensitive:
        cohort: output/prevalent_cohort*.dta   

  generate_analysis_dataset_incident:
    run: stata-mp:latest analysis/001_cr_define_covariates_incident.do
    needs: [generate_study_population_incident]
    outputs:
      highly_sensitive:
        cohort: output/incident_cohort*.dta     

# Generate drug prevalence estimates for incident and prevalent cohorts 102 & 202
  generate_drugprevalence_incident:
    run: stata-mp:latest analysis/102_cr_incident_cohort_prevalence.do
    needs: [generate_analysis_dataset_incident]
    outputs:
      moderately_sensitive:
        output: output/tabfig/incident_prevalences_summary*.csv 
        # graph: output/tabfig/incident_prevalences*.svg

  generate_drugprevalence_prevalent:
    run: stata-mp:latest analysis/202_cr_prevalent_cohort_prevalence.do
    needs: [generate_analysis_dataset_prevalent]
    outputs:
      moderately_sensitive:
        output: output/tabfig/prevalent_prevalences_summary*.csv 
        # graph: output/tabfig/prevalent_prevalences*.svg
