version: '3.0'

expectations:
  population_size: 1000

actions:
  #Study definition 
  generate_study_population_prevalent:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_prevalent
    outputs:
      highly_sensitive:
        cohort: output/input_prevalent.csv

  generate_study_population_incident:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_incident
    outputs:
      highly_sensitive:
        cohort: output/input_incident.csv      